using ContractDiscovery.Generator.Protocol;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Globalization;
using System.Reflection;
using System.Text;

namespace ContractDiscovery.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class ContractDiscoveryGenerator : IIncrementalGenerator
{
    private static string RegistrationAttributeMetadataName => field ??= typeof(GeneratorContractRegistrationAttribute<>).FullName;

    private static string ContractEnumMetadataName => field ??= typeof(DemoContract).FullName;

    private static readonly DiagnosticDescriptor s_missingContract = new(
        id: "CD001",
        title: "Required generator contract is missing",
        messageFormat: "Required contract '{0}' is not registered",
        category: "ContractDiscovery",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor s_duplicateContract = new(
        id: "CD002",
        title: "Generator contract is registered more than once",
        messageFormat: "Contract '{0}' is registered by both '{1}' and '{2}'",
        category: "ContractDiscovery",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static postInit =>
        {
            postInit.AddSource("DemoContract.g.cs", SourceText.FromEmbedded<DemoContract>());
            postInit.AddSource("GeneratorContractRegistrationAttribute.g.cs", SourceText.FromEmbedded(typeof(GeneratorContractRegistrationAttribute<>)));
        });

        context.RegisterSourceOutput(context.CompilationProvider,
            static (sourceContext, compilation) => Generate(sourceContext, compilation));
    }

    private static void Generate(SourceProductionContext context, Compilation compilation)
    {
        Dictionary<DemoContract, INamedTypeSymbol> contracts = [];
        bool hasErrors = false;

        foreach (IAssemblySymbol assembly in EnumerateAssemblies(compilation))
        {
            foreach (INamedTypeSymbol type in EnumerateTypes(assembly.GlobalNamespace))
            {
                foreach (AttributeData attribute in type.GetAttributes())
                {
                    if (!TryReadContract(attribute, out DemoContract contract))
                    {
                        continue;
                    }

                    if (contracts.TryGetValue(contract, out INamedTypeSymbol? existing))
                    {
                        context.ReportDiagnostic(Diagnostic.Create(
                            s_duplicateContract,
                            type.Locations.FirstOrDefault(),
                            contract,
                            existing.ToDisplayString(),
                            type.ToDisplayString()));
                        hasErrors = true;
                        continue;
                    }

                    contracts.Add(contract, type);
                }
            }
        }

        if (!contracts.TryGetValue(DemoContract.Service, out INamedTypeSymbol? serviceType))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                s_missingContract,
                Location.None,
                DemoContract.Service));
            return;
        }

        if (hasErrors)
        {
            return;
        }

        string serviceTypeName = serviceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        string source = $$"""
            // <auto-generated />
            namespace ContractDiscovery.Generated;

            internal static class ResolvedContracts
            {
                internal static {{serviceTypeName}} CreateService()
                    => new {{serviceTypeName}}();
            }
            """;

        context.AddSource("ResolvedContracts.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static bool TryReadContract(AttributeData attribute, out DemoContract contract)
    {
        contract = default;

        INamedTypeSymbol? attributeType = attribute.AttributeClass;
        if (attributeType is null ||
            GetFullMetadataName(attributeType.OriginalDefinition) != RegistrationAttributeMetadataName ||
            attributeType.TypeArguments.Length != 1 ||
            attributeType.TypeArguments[0] is not INamedTypeSymbol contractType ||
            GetFullMetadataName(contractType.OriginalDefinition) != ContractEnumMetadataName ||
            attribute.ConstructorArguments.Length != 1)
        {
            return false;
        }

        object? value = attribute.ConstructorArguments[0].Value;
        if (value is null)
        {
            return false;
        }

        int rawValue = Convert.ToInt32(value, CultureInfo.InvariantCulture);
        if (!Enum.IsDefined(typeof(DemoContract), rawValue))
        {
            return false;
        }

        contract = (DemoContract)rawValue;
        return true;
    }

    private static ImmutableArray<IAssemblySymbol> EnumerateAssemblies(Compilation compilation)
    {
        ImmutableArray<IAssemblySymbol>.Builder assemblies = ImmutableArray.CreateBuilder<IAssemblySymbol>();
        HashSet<IAssemblySymbol> seen = new(SymbolEqualityComparer.Default);

        if (seen.Add(compilation.Assembly))
        {
            assemblies.Add(compilation.Assembly);
        }

        foreach (MetadataReference reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assembly &&
                seen.Add(assembly))
            {
                assemblies.Add(assembly);
            }
        }

        return assemblies.ToImmutable();
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateTypes(INamespaceSymbol ns)
    {
        foreach (INamespaceSymbol childNamespace in ns.GetNamespaceMembers())
        {
            foreach (INamedTypeSymbol type in EnumerateTypes(childNamespace))
            {
                yield return type;
            }
        }

        foreach (INamedTypeSymbol type in ns.GetTypeMembers())
        {
            foreach (INamedTypeSymbol candidate in EnumerateTypeAndNestedTypes(type))
            {
                yield return candidate;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateTypeAndNestedTypes(INamedTypeSymbol type)
    {
        yield return type;

        foreach (INamedTypeSymbol nestedType in type.GetTypeMembers())
        {
            foreach (INamedTypeSymbol candidate in EnumerateTypeAndNestedTypes(nestedType))
            {
                yield return candidate;
            }
        }
    }

    private static string GetFullMetadataName(INamedTypeSymbol type)
    {
        StringBuilder builder = new();
        AppendMetadataName(builder, type);
        return builder.ToString();
    }

    private static void AppendMetadataName(StringBuilder builder, INamedTypeSymbol type)
    {
        if (type.ContainingType is not null)
        {
            AppendMetadataName(builder, type.ContainingType);
            builder.Append('+');
        }
        else if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append(type.ContainingNamespace.ToDisplayString());
            builder.Append('.');
        }

        builder.Append(type.MetadataName);
    }
}
