<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Wkg.EntityFrameworkCore\Wkg.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\Wkg.EntityFrameworkCore.SourceGeneration\Wkg.EntityFrameworkCore.SourceGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </ProjectReference>
    </ItemGroup>
</Project>
